@startuml daily workflow
start
:update schedule;

if (schedule empty?) then (yes)
  :notify user with empty schedule;
else (no)
  :send user the respective task;
  :ask user if he did the task;

  if (user did task within the day?) then (yes)
    note right 
    if the user does not reply within the 
    day it will count task not fulfilled
    end note
    :remove task from queue/schedule;
    :move time forward;
  else (no)
  
    if (debt-free mode?) then (yes)
    else (no)
      :move time forward;
      :merge tasks that reached the deadline;
    endif

  endif

endif
:wait for the next day;
stop
@enduml